#!/usr/bin/env node
/**
 * Capture seed: fills a throwaway Applye database with the demo persona and the
 * job history the documentation screenshots need.
 *
 * WHY THIS EXISTS. Every guide screenshot has to show the same person on the
 * same day, or the docs look assembled from three different apps. Typing eight
 * jobs, their statuses, their interview rounds and their dates by hand before
 * every re-shoot is both slow and unrepeatable; a re-shoot two hours later
 * would show different relative dates and a different dashboard.
 *
 * WHAT IT DELIBERATELY DOES NOT DO. It writes only rows a user could have
 * produced by using the app: a profile, jobs, applications, interview stages,
 * status history and Discover source rows. It never fabricates AI output.
 * Scores, tailored CVs, gap answers and pitch text are generated by running the
 * real features against a real provider, because those screens are exactly what
 * the documentation is making claims about.
 *
 * NO REAL DATA. Every company is invented. Contact details use example.com,
 * which RFC 2606 reserves so it can never belong to anyone.
 *
 * SAFETY. Refuses to run unless --i-know-this-wipes-the-db is passed, and it
 * always writes a timestamped copy of the current database next to it first.
 * Point it at a capture database, never at one you use.
 *
 * Usage:
 *   node tools/capture/seed.mjs --i-know-this-wipes-the-db
 *   node tools/capture/seed.mjs --i-know-this-wipes-the-db --db /path/to/applye.db
 *
 * The app must be closed while this runs: SQLite in WAL mode will happily
 * accept the writes, but a running app holds its own cached state and would
 * overwrite them on the next save.
 */

import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const DEFAULT_DB = join(homedir(), 'Library', 'Application Support', 'dev.applye.app', 'applye.db');

/** Fixed clock. Every relative date in the seed is derived from the run time,
 * so "3 days from now" stays 3 days from now on a re-shoot next week. */
const NOW = new Date();

function iso(daysFromNow, hour = 10, minute = 0) {
  const d = new Date(NOW);
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function parseArgs(argv) {
  const args = { db: DEFAULT_DB, confirmed: false };
  for (let i = 2; i < argv.length; i += 1) {
    if (argv[i] === '--i-know-this-wipes-the-db') args.confirmed = true;
    else if (argv[i] === '--db') args.db = argv[(i += 1)];
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  return args;
}

function sqlite(db, sql) {
  return execFileSync('sqlite3', [db, sql], { encoding: 'utf8' });
}

/**
 * The app's own `jd_hash`, reimplemented: FNV-1a over whitespace-normalised,
 * lowercased text (see `stable_hash` in src-tauri/src/db.rs). It matters
 * visually, not just for dedupe - the job page prints the first twelve
 * characters of this hash under the title, so a made-up value like
 * "capture-seed-1" would put the name of this script on a screenshot.
 */
function stableHash(text) {
  const normalized = text.split(/\s+/).filter(Boolean).join(' ').toLowerCase();
  let hash = 0xcbf29ce484222325n;
  const prime = 0x100000001b3n;
  const mask = 0xffffffffffffffffn;
  for (const byte of Buffer.from(normalized, 'utf8')) {
    hash = (hash ^ BigInt(byte)) & mask;
    hash = (hash * prime) & mask;
  }
  return hash.toString(16).padStart(16, '0');
}

function q(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

// --------------------------------------------------------------- the persona

const PROFILE_MD = `# Mira Halvorsen
Senior Frontend Engineer

## Contact
- First name: Mira
- Last name: Halvorsen
- Location: Berlin, Germany
- Email: mira.halvorsen@example.com
- Phone: +49 30 0000 0000
- Website: example.com/mira
- LinkedIn: linkedin.com/in/example-mira

## Experience
### Senior Frontend Engineer - Halden Interactive
Berlin, Germany · 2022 - Present
- Led the rebuild of a customer console used by 12,000 accounts, moving it off a jQuery admin without a feature freeze.
- Cut the largest bundle from 1.9 MB to 640 KB by splitting the editor route and dropping three overlapping date libraries.
- Introduced accessibility review as a release gate; the console now passes WCAG 2.2 AA on every shipped screen.
- Mentored three engineers, two of whom now run their own areas.

### Frontend Engineer - Sorenson Grid
Oslo, Norway · 2019 - 2022
- Built the component library six product teams still ship on, including its dark theme and its documentation site.
- Owned the migration from a hand-rolled build to a monorepo with cached tasks, cutting CI from 22 to 7 minutes.
- Wrote the offline-tolerant form layer used by field engineers on unreliable connections.

## Skills
TypeScript, Angular, RxJS, Node.js, Nx, Playwright, Jest, CSS architecture, Web performance, Accessibility (WCAG 2.2), Design systems, SQL

## Education
BSc Computer Science, University of Bergen (2015 - 2018)

## Languages
English C1, Norwegian native, German B1

## Compensation
85000 - 105000 EUR per year

## Notes
Open to hybrid in Berlin or remote within CET +/- 2. Not looking to relocate.
`;

const ARCHETYPES = [
  {
    name: 'Senior Frontend Engineer',
    fit: 'primary',
    sellWhen:
      'The role owns a product surface end to end and expects the frontend to set its own quality bar.',
  },
  {
    name: 'Frontend Platform Engineer',
    fit: 'secondary',
    sellWhen:
      'The team runs a design system or a monorepo and needs someone who has already paid for those mistakes once.',
  },
  {
    name: 'UI Engineer',
    fit: 'adjacent',
    sellWhen:
      'The work is closer to craft than to architecture, and the pay band still clears the target.',
  },
];

// ------------------------------------------------------------------ the jobs
//
// Statuses and dates are chosen so the Dashboard has something in every tile:
// one interview scheduled three days out, one follow-up already overdue, one
// offer, and a rejection so the funnel is not a straight line. Legitimacy tiers
// cover all three values the app assigns: green, yellow and red.

const JOBS = [
  {
    company: 'Northlane Systems',
    title: 'Senior Frontend Engineer',
    location: 'Berlin, Germany',
    salaryMin: 78000,
    tier: 'green',
    notes: null,
    createdDaysAgo: 21,
    status: 'interview',
    appliedDaysAgo: 18,
    followUpDaysAgo: null,
    jd: `Own our customer console end to end. Angular 20, TypeScript, RxJS, a Node BFF.
You will lead the migration off the legacy dashboard, set the testing bar and review
most of the frontend work that ships.

Requirements: 5+ years with a component framework, strong TypeScript, accessibility
audit experience, German B1 for internal meetings.

EUR 78,000 - 92,000 per year. Hybrid, two days on site in Berlin.`,
    // Statuses are the ones create_interview_stage_core writes and the UI reads
    // (see InterviewStageStatus): a cleared round is `passed`, a booked one is
    // `scheduled` with a date, and a round that exists but has no date yet is
    // `awaiting_scheduling`.
    //
    // Only two rounds here, and the booked one is deliberately last. The
    // Dashboard's "upcoming interviews" reads the CURRENT stage, and
    // db_pipeline_cards defines that as the highest stage_order that is not
    // rejected or cancelled (see applications.rs). Adding a third, undated
    // round would make the undated one current and the counter would read zero
    // while an interview sat three days away. The three-round timeline lives on
    // Pellworm Digital instead.
    stages: [
      { order: 1, type: 'hr_screen', label: 'Screening call', daysFromNow: -9, status: 'passed' },
      {
        order: 2,
        type: 'technical',
        label: 'Technical round',
        daysFromNow: 3,
        status: 'scheduled',
      },
    ],
  },
  {
    company: 'Marlowe & Fen',
    title: 'Staff Frontend Engineer',
    location: 'Berlin, Germany',
    salaryMin: 100000,
    tier: 'green',
    notes: null,
    createdDaysAgo: 40,
    status: 'offer',
    appliedDaysAgo: 35,
    followUpDaysAgo: null,
    jd: `Staff role across three product teams. Set frontend direction, own the architecture
of the next client, mentor six engineers. Angular, TypeScript, a shared design system,
a heavy accessibility commitment.

Requirements: 8+ years, prior staff or principal scope, migrations delivered without a
freeze.

EUR 100,000 - 115,000 per year. Berlin or remote within CET +/- 2.`,
    stages: [],
  },
  {
    company: 'Kestrel Analytics',
    title: 'Frontend Platform Engineer',
    location: 'Remote, EU',
    salaryMin: 75000,
    tier: 'green',
    notes: null,
    createdDaysAgo: 14,
    status: 'applied',
    appliedDaysAgo: 12,
    followUpDaysAgo: 4,
    jd: `Platform team of four. Own the design-system package, the build pipeline and the
release train for six product teams. Angular, Nx monorepo, Storybook, Playwright.

Requirements: monorepo experience, comfort with build tooling, an eye for API design in
shared components.

EUR 75,000 - 88,000 per year. Remote within the EU.`,
    stages: [],
  },
  {
    company: 'Pellworm Digital',
    title: 'Senior Web Engineer',
    location: 'Hamburg, Germany',
    salaryMin: 80000,
    tier: 'green',
    notes: null,
    createdDaysAgo: 9,
    status: 'interview',
    appliedDaysAgo: 7,
    followUpDaysAgo: null,
    jd: `Rebuilding a booking flow that serves 40,000 sessions a day. TypeScript everywhere,
Angular on the front, a small Rust service behind it. Every release is measured against a
Core Web Vitals budget.

Requirements: senior frontend experience, measurable performance work, weekly pairing
with designers.

EUR 80,000 - 95,000 per year. Hybrid in Hamburg.`,
    // The three-round timeline guide/interview-timeline.png needs: one cleared,
    // one booked, one that exists but has no date yet. It sits here rather than
    // on Northlane because the undated round becomes the current stage and would
    // empty the Dashboard's upcoming-interview counter.
    stages: [
      { order: 1, type: 'hr_screen', label: 'Screening call', daysFromNow: -4, status: 'passed' },
      {
        order: 2,
        type: 'technical',
        label: 'Technical round',
        daysFromNow: 9,
        status: 'scheduled',
      },
      {
        order: 3,
        type: 'final',
        label: 'Final conversation',
        daysFromNow: null,
        status: 'awaiting_scheduling',
      },
    ],
  },
  {
    company: 'Vantaform GmbH',
    title: 'Fullstack Engineer (frontend-heavy)',
    location: 'Munich, Germany',
    salaryMin: null,
    tier: 'yellow',
    notes: 'No salary range stated.',
    createdDaysAgo: 6,
    status: 'saved',
    appliedDaysAgo: null,
    followUpDaysAgo: null,
    jd: `Roughly 70% frontend, 30% Node services. An internal logistics tool used by 300
staff: dense tables, offline-tolerant forms, printable reports.

Requirements: TypeScript, a component framework, some SQL, German B2 for stakeholder
interviews.

Salary: competitive. Hybrid in Munich.`,
    stages: [],
  },
  {
    company: 'Cindertree Studio',
    title: 'Frontend Developer',
    location: 'Remote, Europe',
    salaryMin: null,
    tier: 'yellow',
    notes: 'No salary range stated. Team size not given.',
    createdDaysAgo: 5,
    status: 'saved',
    appliedDaysAgo: null,
    followUpDaysAgo: null,
    jd: `Agency work: three to five client projects a year, mostly marketing sites and
configurators. Expect a new codebase every quarter and a lot of animation work.

Requirements: solid CSS, one component framework, comfort switching stacks, portfolio
required.`,
    stages: [],
  },
  {
    company: 'Umbra Labs',
    title: 'Angular Engineer',
    location: 'Berlin, Germany',
    salaryMin: 70000,
    tier: 'red',
    notes:
      'Unpaid trial task. "We are a family" with no team size. Weekend releases stated as normal.',
    createdDaysAgo: 4,
    status: 'saved',
    appliedDaysAgo: null,
    followUpDaysAgo: null,
    jd: `Small team, fast pace. We are a family and we work hard and play hard. Looking for
someone stress-resistant who can wear many hats and is not a clock-watcher. Occasional
weekend releases before a launch are normal here.

Process: unpaid trial task first, interview after.

EUR 70,000 per year.`,
    stages: [],
  },
  {
    company: 'Roosterhill Media',
    title: 'UI Engineer',
    location: 'Cologne, Germany',
    salaryMin: 62000,
    tier: 'green',
    notes: null,
    createdDaysAgo: 47,
    status: 'rejected',
    appliedDaysAgo: 44,
    followUpDaysAgo: null,
    jd: `Publishing house, editorial tooling. Maintain the article editor and the newsletter
builder the newsroom uses every day.

Requirements: 2+ years frontend, care for editorial workflows, German C1 because the
newsroom works in German.

EUR 62,000 - 70,000 per year. On site in Cologne.`,
    stages: [],
  },
];

/** A user-added feed alongside the built-in sources, so the Sources drawer has
 * a row with a last-scan line. The URL is a reserved example domain and is
 * never fetched by this script. */
const USER_SOURCE = {
  name: 'Frontend roles (EU)',
  type: 'rss',
  url: 'https://jobs.example.com/frontend.xml',
  lastScanDaysAgo: 0,
};

// ----------------------------------------------------------------- execution

function main() {
  const args = parseArgs(process.argv);

  if (!args.confirmed) {
    console.error(
      'Refusing to run: this deletes every job, application and profile in the\n' +
        'target database. Re-run with --i-know-this-wipes-the-db once you are sure\n' +
        `the target is a capture database and not one you use:\n  ${args.db}`,
    );
    process.exit(1);
  }
  if (!existsSync(args.db)) {
    console.error(`No database at ${args.db}. Launch the app once so it is created.`);
    process.exit(1);
  }

  const stamp = NOW.toISOString().replace(/[:.]/g, '-');
  const backup = `${args.db}.pre-seed-${stamp}`;
  copyFileSync(args.db, backup);
  console.log(`Backed up to ${backup}`);

  const sql = [];
  sql.push('PRAGMA foreign_keys = ON;');
  sql.push('BEGIN;');

  // Order matters: children before parents.
  sql.push('DELETE FROM interview_stages;');
  sql.push('DELETE FROM status_history;');
  sql.push('DELETE FROM applications;');
  sql.push('DELETE FROM jobs;');
  sql.push('DELETE FROM profile;');
  sql.push('DELETE FROM sources WHERE is_builtin = 0;');

  sql.push(
    `INSERT INTO profile (id, full_md, target_archetypes, updated_at)
     VALUES (1, ${q(PROFILE_MD)}, ${q(JSON.stringify(ARCHETYPES))}, ${q(iso(0))});`,
  );

  JOBS.forEach((job, index) => {
    const jobId = index + 1;
    const createdAt = iso(-job.createdDaysAgo, 9, 30);
    sql.push(
      `INSERT INTO jobs (id, company, title, jd_text, jd_hash, source, location, language,
         salary_min, hard_filter_passed, created_at, legitimacy_tier, legitimacy_notes,
         imported_from, discover_shown_at, source_url)
       VALUES (${jobId}, ${q(job.company)}, ${q(job.title)}, ${q(job.jd)},
         ${q(stableHash(job.jd))}, ${q('manual')}, ${q(job.location)}, ${q('en')},
         ${q(job.salaryMin)}, 1, ${q(createdAt)}, ${q(job.tier)}, ${q(job.notes)},
         ${q('manual_paste')}, ${q(createdAt)},
         ${q(`https://jobs.example.com/${job.company.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`)});`,
    );

    const appliedAt = job.appliedDaysAgo === null ? null : iso(-job.appliedDaysAgo, 11, 15);
    const followUpAt = job.followUpDaysAgo === null ? null : iso(-job.followUpDaysAgo, 9, 0);
    sql.push(
      `INSERT INTO applications (id, job_id, status, application_method, applied_at,
         follow_up_at, updated_at, salary_range)
       VALUES (${jobId}, ${jobId}, ${q(job.status)},
         ${q(job.appliedDaysAgo === null ? null : 'online_form')}, ${q(appliedAt)},
         ${q(followUpAt)}, ${q(iso(0))},
         ${q(job.salaryMin === null ? null : `EUR ${job.salaryMin.toLocaleString('en-US')}+`)});`,
    );

    if (appliedAt) {
      sql.push(
        `INSERT INTO status_history (application_id, status, changed_at)
         VALUES (${jobId}, ${q('applied')}, ${q(appliedAt)});`,
      );
    }
    if (job.status !== 'saved' && job.status !== 'applied') {
      sql.push(
        `INSERT INTO status_history (application_id, status, changed_at)
         VALUES (${jobId}, ${q(job.status)}, ${q(iso(-Math.max(1, (job.appliedDaysAgo ?? 7) - 5), 14))});`,
      );
    }

    job.stages.forEach((stage) => {
      sql.push(
        `INSERT INTO interview_stages (application_id, stage_order, stage_type, stage_label,
           scheduled_at, status, stage_language)
         VALUES (${jobId}, ${stage.order}, ${q(stage.type)}, ${q(stage.label)},
           ${q(stage.daysFromNow === null ? null : iso(stage.daysFromNow, 14, 0))},
           ${q(stage.status)}, ${q('en')});`,
      );
    });
  });

  sql.push(
    `INSERT INTO sources (name, type, url, is_builtin, is_enabled, geo_tags_json,
       legality_note, created_at, last_scan_at)
     VALUES (${q(USER_SOURCE.name)}, ${q(USER_SOURCE.type)}, ${q(USER_SOURCE.url)}, 0, 1,
       ${q(JSON.stringify(['eu', 'de']))},
       ${q('User-added RSS feed - public, machine-readable.')},
       ${q(iso(-30))}, ${q(iso(-USER_SOURCE.lastScanDaysAgo, 8, 5))});`,
  );

  sql.push('COMMIT;');

  sqlite(args.db, sql.join('\n'));

  const counts = sqlite(
    args.db,
    "SELECT 'jobs=' || (SELECT COUNT(*) FROM jobs) || " +
      "' applications=' || (SELECT COUNT(*) FROM applications) || " +
      "' stages=' || (SELECT COUNT(*) FROM interview_stages) || " +
      "' sources=' || (SELECT COUNT(*) FROM sources) || " +
      "' profile=' || (SELECT COUNT(*) FROM profile);",
  ).trim();

  console.log(`Seeded: ${counts}`);
  console.log('Still to do by hand, because these are AI output and must be real:');
  console.log('  - score one job (Northlane Systems) so guide/score-result.png is genuine');
  console.log('  - run the tailor wizard once for guide/tailor-wizard.mp4 and gap-dialog.png');
  console.log('  - import a CV so the document library has entries');
}

main();
