#!/usr/bin/env node
/**
 * Capture seed: fills a throwaway Applye database with the demo persona and the
 * job history the documentation screenshots need.
 *
 * WHY THIS EXISTS. Every guide screenshot has to show the same person on the
 * same day, or the docs look assembled from three different apps. Typing eight
 * jobs, their statuses, their interview rounds and their dates by hand before
 * every re-shoot is both slow and unrepeatable; a re-shoot two hours later
 * would show different relative dates and a different dashboard.
 *
 * WHAT IT DELIBERATELY DOES NOT DO. It writes only rows a user could have
 * produced by using the app: a profile, jobs, applications, interview stages,
 * status history and Discover source rows. It never fabricates AI output.
 * Scores, tailored CVs, gap answers and pitch text are generated by running the
 * real features against a real provider, because those screens are exactly what
 * the documentation is making claims about.
 *
 * NO REAL DATA. Every company is invented. Contact details use example.com,
 * which RFC 2606 reserves so it can never belong to anyone.
 *
 * SAFETY. Refuses to run unless --i-know-this-wipes-the-db is passed, and it
 * always writes a timestamped copy of the current database next to it first.
 * Point it at a capture database, never at one you use.
 *
 * Usage:
 *   node tools/capture/seed.mjs --i-know-this-wipes-the-db
 *   node tools/capture/seed.mjs --i-know-this-wipes-the-db --db /path/to/applye.db
 *
 * The app must be closed while this runs: SQLite in WAL mode will happily
 * accept the writes, but a running app holds its own cached state and would
 * overwrite them on the next save.
 */

import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { ARCHETYPES, PROFILE_MD } from './seed-persona.mjs';
import { JOBS } from './seed-jobs.mjs';
import { DISCOVER_JOBS, USER_SOURCE } from './seed-discover.mjs';

const DEFAULT_DB = join(homedir(), 'Library', 'Application Support', 'dev.applye.app', 'applye.db');

/** Fixed clock. Every relative date in the seed is derived from the run time,
 * so "3 days from now" stays 3 days from now on a re-shoot next week. */
const NOW = new Date();

function iso(daysFromNow, hour = 10, minute = 0) {
  const d = new Date(NOW);
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function parseArgs(argv) {
  const args = { db: DEFAULT_DB, confirmed: false, discoverOnly: false };
  for (let i = 2; i < argv.length; i += 1) {
    if (argv[i] === '--i-know-this-wipes-the-db') args.confirmed = true;
    // Re-inserts only the Discover rows, leaving everything else alone. Exists
    // because a full re-seed also drops the profile, and the scoring profile on
    // it is real AI output that costs a call to regenerate.
    else if (argv[i] === '--discover-only') args.discoverOnly = true;
    else if (argv[i] === '--db') args.db = argv[(i += 1)];
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  return args;
}

function sqlite(db, sql) {
  return execFileSync('sqlite3', [db, sql], { encoding: 'utf8' });
}

/**
 * The app's own `jd_hash`, reimplemented: FNV-1a over whitespace-normalised,
 * lowercased text (see `stable_hash` in src-tauri/src/db.rs). It matters
 * visually, not just for dedupe - the job page prints the first twelve
 * characters of this hash under the title, so a made-up value like
 * "capture-seed-1" would put the name of this script on a screenshot.
 */
function stableHash(text) {
  const normalized = text.split(/\s+/).filter(Boolean).join(' ').toLowerCase();
  let hash = 0xcbf29ce484222325n;
  const prime = 0x100000001b3n;
  const mask = 0xffffffffffffffffn;
  for (const byte of Buffer.from(normalized, 'utf8')) {
    hash = (hash ^ BigInt(byte)) & mask;
    hash = (hash * prime) & mask;
  }
  return hash.toString(16).padStart(16, '0');
}

function q(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

// ----------------------------------------------------------------- execution

/** Inserts the Discover inbox rows. Shared by the full seed and --discover-only. */
function pushDiscoverJobs(sql) {
  DISCOVER_JOBS.forEach((job, index) => {
    const jobId = 100 + index;
    const seen = new Date(NOW.getTime() - job.hoursAgo * 3600_000).toISOString();
    const slug = job.company.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    sql.push(
      `INSERT INTO jobs (id, company, title, jd_text, jd_hash, source, location, language,
         salary_min, hard_filter_passed, created_at, legitimacy_tier, imported_from,
         discover_shown_at, discover_dismissed, source_url)
       VALUES (${jobId}, ${q(job.company)}, ${q(job.title)}, ${q(job.jd)},
         ${q(stableHash(job.jd))}, ${q('Frontend roles (EU)')}, ${q(job.location)}, ${q('en')},
         ${q(job.salaryMin)}, 1, ${q(seen)}, ${q('green')}, ${q('discover_scan')},
         NULL, 0, ${q(`https://jobs.example.com/${slug}`)});`,
    );
  });
}

function main() {
  const args = parseArgs(process.argv);

  if (!args.confirmed) {
    console.error(
      'Refusing to run: this deletes every job, application and profile in the\n' +
        'target database. Re-run with --i-know-this-wipes-the-db once you are sure\n' +
        `the target is a capture database and not one you use:\n  ${args.db}`,
    );
    process.exit(1);
  }
  if (!existsSync(args.db)) {
    console.error(`No database at ${args.db}. Launch the app once so it is created.`);
    process.exit(1);
  }

  const stamp = NOW.toISOString().replace(/[:.]/g, '-');
  const backup = `${args.db}.pre-seed-${stamp}`;
  copyFileSync(args.db, backup);
  console.log(`Backed up to ${backup}`);

  const sql = [];
  sql.push('PRAGMA foreign_keys = ON;');
  sql.push('BEGIN;');

  if (args.discoverOnly) {
    sql.push("DELETE FROM jobs WHERE imported_from = 'discover_scan';");
    pushDiscoverJobs(sql);
    sql.push('COMMIT;');
    sqlite(args.db, sql.join('\n'));
    console.log(
      `Discover rows only: ${sqlite(args.db, "SELECT COUNT(*) FROM jobs WHERE imported_from = 'discover_scan';").trim()} inserted`,
    );
    return;
  }

  // Order matters: children before parents.
  sql.push('DELETE FROM interview_stages;');
  sql.push('DELETE FROM status_history;');
  sql.push('DELETE FROM applications;');
  sql.push('DELETE FROM jobs;');
  sql.push('DELETE FROM profile;');
  sql.push('DELETE FROM sources WHERE is_builtin = 0;');

  sql.push(
    `INSERT INTO profile (id, full_md, target_archetypes, updated_at)
     VALUES (1, ${q(PROFILE_MD)}, ${q(JSON.stringify(ARCHETYPES))}, ${q(iso(0))});`,
  );

  JOBS.forEach((job, index) => {
    const jobId = index + 1;
    const createdAt = iso(-job.createdDaysAgo, 9, 30);
    sql.push(
      `INSERT INTO jobs (id, company, title, jd_text, jd_hash, source, location, language,
         salary_min, hard_filter_passed, created_at, legitimacy_tier, legitimacy_notes,
         imported_from, discover_shown_at, source_url)
       VALUES (${jobId}, ${q(job.company)}, ${q(job.title)}, ${q(job.jd)},
         ${q(stableHash(job.jd))}, ${q('manual')}, ${q(job.location)}, ${q('en')},
         ${q(job.salaryMin)}, 1, ${q(createdAt)}, ${q(job.tier)}, ${q(job.notes)},
         ${q('manual_paste')}, ${q(createdAt)},
         ${q(`https://jobs.example.com/${job.company.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`)});`,
    );

    const appliedAt = job.appliedDaysAgo === null ? null : iso(-job.appliedDaysAgo, 11, 15);
    const followUpAt = job.followUpDaysAgo === null ? null : iso(-job.followUpDaysAgo, 9, 0);
    sql.push(
      `INSERT INTO applications (id, job_id, status, application_method, applied_at,
         follow_up_at, updated_at, salary_range)
       VALUES (${jobId}, ${jobId}, ${q(job.status)},
         ${q(job.appliedDaysAgo === null ? null : 'online_form')}, ${q(appliedAt)},
         ${q(followUpAt)}, ${q(iso(0))},
         ${q(job.salaryMin === null ? null : `EUR ${job.salaryMin.toLocaleString('en-US')}+`)});`,
    );

    if (appliedAt) {
      sql.push(
        `INSERT INTO status_history (application_id, status, changed_at)
         VALUES (${jobId}, ${q('applied')}, ${q(appliedAt)});`,
      );
    }
    if (job.status !== 'saved' && job.status !== 'applied') {
      sql.push(
        `INSERT INTO status_history (application_id, status, changed_at)
         VALUES (${jobId}, ${q(job.status)}, ${q(iso(-Math.max(1, (job.appliedDaysAgo ?? 7) - 5), 14))});`,
      );
    }

    job.stages.forEach((stage) => {
      sql.push(
        `INSERT INTO interview_stages (application_id, stage_order, stage_type, stage_label,
           scheduled_at, status, stage_language)
         VALUES (${jobId}, ${stage.order}, ${q(stage.type)}, ${q(stage.label)},
           ${q(stage.daysFromNow === null ? null : iso(stage.daysFromNow, 14, 0))},
           ${q(stage.status)}, ${q('en')});`,
      );
    });
  });

  pushDiscoverJobs(sql);

  sql.push(
    `INSERT INTO sources (name, type, url, is_builtin, is_enabled, geo_tags_json,
       legality_note, created_at, last_scan_at)
     VALUES (${q(USER_SOURCE.name)}, ${q(USER_SOURCE.type)}, ${q(USER_SOURCE.url)}, 0, 1,
       ${q(JSON.stringify(['eu', 'de']))},
       ${q('User-added RSS feed - public, machine-readable.')},
       ${q(iso(-30))}, ${q(iso(-USER_SOURCE.lastScanDaysAgo, 8, 5))});`,
  );

  sql.push('COMMIT;');

  sqlite(args.db, sql.join('\n'));

  const counts = sqlite(
    args.db,
    "SELECT 'jobs=' || (SELECT COUNT(*) FROM jobs) || " +
      "' applications=' || (SELECT COUNT(*) FROM applications) || " +
      "' stages=' || (SELECT COUNT(*) FROM interview_stages) || " +
      "' sources=' || (SELECT COUNT(*) FROM sources) || " +
      "' profile=' || (SELECT COUNT(*) FROM profile);",
  ).trim();

  console.log(`Seeded: ${counts}`);
  console.log('Still to do by hand, because these are AI output and must be real:');
  console.log('  - score one job (Northlane Systems) so guide/score-result.png is genuine');
  console.log('  - run the tailor wizard once for guide/tailor-wizard.mp4 and gap-dialog.png');
  console.log('  - import a CV so the document library has entries');
}

main();
