#!/usr/bin/env bash
#
# Builds apps/web/public/press/applye-press-kit.zip, the single archive the
# press page offers instead of asking a journalist to email for assets.
#
# Everything in it already exists in the repository. The point of the script is
# that the archive is assembled rather than curated by hand: a zip built once by
# dragging files into it goes stale the first time a wordmark changes, and
# nobody notices until a publication uses the old one.
#
#   bash apps/web/tools/build-press-kit.sh
#
# Deterministic on purpose: files are added in a fixed order and the zip is
# built with -X, so rebuilding without changing an input produces the same
# bytes and does not show up as a diff.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OUT="$REPO/apps/web/public/press/applye-press-kit.zip"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

KIT="$STAGE/applye-press-kit"
mkdir -p "$KIT/wordmark" "$KIT/icon" "$KIT/screenshots"

# Wordmarks: the lockup, light and dark. Generated by docs/assets/brand/wordmark.mjs.
cp "$REPO/docs/assets/brand/wordmark-light.svg" "$KIT/wordmark/"
cp "$REPO/docs/assets/brand/wordmark-dark.svg" "$KIT/wordmark/"

# App icon and the bare symbol, both themes.
cp "$REPO/apps/web/public/brand/applye-icon-light.svg" "$KIT/icon/"
cp "$REPO/apps/web/public/brand/applye-icon-dark.svg" "$KIT/icon/"
cp "$REPO/apps/web/public/brand/applye-symbol-light.svg" "$KIT/icon/"
cp "$REPO/apps/web/public/brand/applye-symbol-dark.svg" "$KIT/icon/"

# Screenshots: the three already published in the README, so what a publication
# runs is what a reader has seen. Not the whole set - a press kit is a choice,
# not a dump.
cp "$REPO/docs/assets/screens/dashboard.png" "$KIT/screenshots/"
cp "$REPO/docs/assets/screens/job-detail.png" "$KIT/screenshots/"
cp "$REPO/docs/assets/screens/pipeline.png" "$KIT/screenshots/"
cp "$REPO/docs/assets/hero-banner.png" "$KIT/screenshots/"

cat > "$KIT/README.txt" <<'TXT'
Applye press kit
================

Applye is an open-source, local-first desktop app for an AI-powered job search.
It scores roles against your profile, tailors your CV per posting, drafts cover
letters and follow-ups, preps you for interviews, and tracks the pipeline - all
on your machine. No cloud, no account, no telemetry. You bring the AI you
already pay for, and every submission stays a human decision.

  Website   https://applye.dev
  Source    https://github.com/vitala89/applye
  Licence   MIT

Tagline:  Drafting is automated. Submitting is not.

What is in here
---------------

  wordmark/     The logo lockup, for light and dark backgrounds. SVG.
  icon/         The app icon and the bare symbol, both themes. SVG.
  screenshots/  Three product screens and the hero banner. PNG.

Using the marks
---------------

Please do not stretch, recolour, rotate, or add effects to the wordmark. Keep
clear space around it of at least the height of the mark beside the word. Use
the light file on light backgrounds and the dark file on dark ones; the indigo
bar is the same in both and should not be recoloured.

The screenshots are of the running application against an invented demo
profile. No real person, employer, or job posting appears in any of them.

Questions, or an asset you need that is not here: the contact address is on
https://applye.dev/press
TXT

# Reproducibility takes three things, not one: -X drops uid/gid and extended
# attributes so the output does not vary with whoever ran it, find|sort fixes
# the order, and the timestamps have to be pinned - a zip stores the mtime of
# every entry, and copying into a temp directory stamps all of them with the
# moment the script ran. Without this line, rebuilding an unchanged kit
# produces different bytes and lands as a meaningless diff.
find "$KIT" -exec touch -t 202601010000.00 {} +

cd "$STAGE"
mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"
find applye-press-kit -type f | sort | zip -q -X "$OUT" -@

echo "$OUT"
unzip -l "$OUT" | tail -n +2
