import { ChangeDetectionStrategy, Component, inject, input, output } from '@angular/core';
import { ChevronDown, Info, LucideAngularModule, Mic, RefreshCw, Sparkles } from 'lucide-angular';
import { ScoringState } from '@applye/core';
import { TranslateService } from '@applye/i18n';
import { ButtonDirective } from '@applye/ui';
import { ScoringSummaryComponent } from '../scoring-summary.component';
import { ProfileFreshnessChipsComponent } from './profile-freshness-chips.component';

/**
 * Profile's AI Tools section: the scoring profile and the elevator pitch, each
 * with its freshness against the markdown it was generated from.
 *
 * It owns no state and runs no AI call. Both artefacts are generated by the
 * page - the calls read `fullMd`, write the profile row and refresh
 * `savedMdHash`, which is the page's own save path - so this section takes what
 * to show and emits when the user asks for it. That is a wider boundary than
 * the five editor sections, eleven inputs rather than two, but they are flat
 * scalars rather than a protocol threaded per field, which is the line
 * `cv-preview` failed to stay on the right side of.
 */
@Component({
  selector: 'app-profile-ai-tools',
  standalone: true,
  imports: [
    ButtonDirective,
    LucideAngularModule,
    ScoringSummaryComponent,
    ProfileFreshnessChipsComponent,
  ],
  templateUrl: './profile-ai-tools.component.html',
  styleUrl: './profile-ai-tools.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProfileAiToolsComponent {
  protected readonly t = inject(TranslateService).t;

  /** Whether either Generate button can run: false while any call or save is in
   * flight, and false with no markdown to generate from. */
  readonly canGenerate = input.required<boolean>();

  readonly scoringOpen = input.required<boolean>();
  readonly scoringState = input.required<ScoringState>();
  readonly scoring = input.required<boolean>();
  readonly scoringJson = input.required<string | null>();
  readonly scoreStatus = input.required<string>();
  readonly scoreError = input.required<boolean>();

  readonly pitchState = input.required<ScoringState>();
  readonly pitching = input.required<boolean>();
  readonly pitchMd = input.required<string | null>();
  readonly pitchStatus = input.required<string>();
  readonly pitchError = input.required<boolean>();

  readonly scoringToggled = output<void>();
  readonly scoringRequested = output<void>();
  readonly pitchRequested = output<void>();

  protected readonly icons = {
    chevron: ChevronDown,
    info: Info,
    pitch: Mic,
    regen: RefreshCw,
    scoring: Sparkles,
  };
}
